# Generated by Django 3.2.16 on 2023-03-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTP_038_backend', '0002_auto_20230308_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinate',
        ),
    ]
