# Generated by Django 3.2.16 on 2023-03-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTP_038_backend', '0002_auto_20230303_1225'),
        ('MTP_038_backend', '0003_delete_coordinate'),
    ]

    operations = [
    ]
